### ISSUE TITLE
Integration Checklist

### ISSUE THREAD

**Issue by willdoran** [ushahidi/comrades-service-proxy#8]
The following steps cover the main steps to test CREES:
## CREES

- [ ] Create a new post of type "Integration Survey"
- [ ] Enter a value in the description field and save they survey
- [ ] The round trip for a Post to be annotated and labelled takes between 1 and 5 minutes.
- [ ] Refresh the post
  - [ ] The annotation field should contain a value
  - [ ] There should be at least a tag of type 'non-related'

## Create a new survey for integration
 - [ ] Add new Survey as normal with two additional elements
  - [ ] Make sure to add a category type field, and to select the appropriate tags
  - [ ] Make sure to add a Markdown field

## Configure a Webhook
 - [ ] Delete all existing webhooks, this must be done from inside each webhook's view
 - [ ] Go to Settings -> Webhooks
 - [ ] Click add a new Webhook button
 - [ ] Name, is only informational can be whatever you want
 - [ ] Shared secret should be set to 'thisisasharedsecretthatislong'
 - [ ] URLS for each service(I recommend creating one of each):
   - [ ] http://comrades-stg-service.ushahidi.com/yodie/annotate
   - [ ] http://comrades-stg-service.ushahidi.com/crees/all
   - [ ] http://comrades-stg-service.ushahidi.com/crees/eventRelated
   - [ ] http://comrades-stg-service.ushahidi.com/crees/eventType
   - [ ] http://comrades-stg-service.ushahidi.com/crees/infoType
 - [ ] Set Event Type
 - [ ] Set Entity Type
 - [ ] Choose your previously created survey
  - [ ] Set the appropriate source and destination fields, for yodie generally Description and Annotation(or whatever you called your mark down field)
 - [ ] Save
 - [ ] Add a new Post of the survey type you associated with the webhook
 - [ ] After 1-5 minutes refresh page and ensure that either a tag or annotation has been added as appropriate
